"""
chunker.py — Custom XML Parser Chunker for Semantic RAG
Extracts <chunk> and <table> tags generated by GPT-4o.
"""
import re
import time
from typing import List, Tuple

from app.logger import rag_logger


class ArabicChunker:
    """
    Parses semantic text extraction from GPT-4o containing <chunk> and <table> tags.
    """
    def __init__(self, chunk_size: int = None, chunk_overlap: int = None):
        # We don't use size/overlap here since GPT-4o does semantic chunking.
        pass

    def _split_into_chunks(self, text: str, max_length: int = 512) -> List[str]:
        if len(text) <= max_length:
            return [text]
        words = text.split()
        chunks = []
        current_chunk = []
        current_len = 0
        for word in words:
            word_len = len(word)
            if current_len + word_len + (1 if current_chunk else 0) > max_length and current_chunk:
                chunks.append(" ".join(current_chunk))
                current_chunk = [word]
                current_len = word_len
            else:
                current_chunk.append(word)
                current_len += word_len + (1 if current_chunk else 0)
        if current_chunk:
            chunks.append(" ".join(current_chunk))
        return chunks

    def chunk_page(self, page_text: str, page_number: int, document_name: str) -> List[dict]:
        if not page_text or not page_text.strip():
            return []

        chunks = []
        
        # Regex to match either <chunk> or <table>
        pattern = re.compile(
            r'(<chunk>(.*?)</chunk>)|(<table>\s*<title>(.*?)</title>\s*<content>(.*?)</content>\s*</table>)',
            re.DOTALL
        )
        
        def add_text_chunks(text: str):
            text = text.strip()
            if len(text) > 20:
                for sub_chunk in self._split_into_chunks(text, 512):
                    if sub_chunk.strip():
                        chunks.append({
                            "text": sub_chunk,
                            "embed_text": sub_chunk,
                            "metadata": {
                                "document_name": document_name,
                                "page_number": page_number,
                                "is_table": False
                            }
                        })

        last_end = 0
        for match in pattern.finditer(page_text):
            # Text before the tag
            raw_text = page_text[last_end:match.start()].strip()
            add_text_chunks(raw_text)
            
            if match.group(1): # It's a <chunk>
                chunk_content = match.group(2).strip()
                add_text_chunks(chunk_content)
            elif match.group(3): # It's a <table>
                title = match.group(4).strip()
                content = match.group(5).strip()
                chunks.append({
                    "text": f"Table: {title}\n\n{content}",
                    "embed_text": title, # Emded only the title for semantic retrieval
                    "metadata": {
                        "document_name": document_name,
                        "page_number": page_number,
                        "is_table": True,
                        "table_title": title
                    }
                })
                
            last_end = match.end()
            
        # Remaining text after last tag
        remaining_text = page_text[last_end:].strip()
        add_text_chunks(remaining_text)
            
        # Add index and length metadata
        for i, c in enumerate(chunks):
            c["metadata"]["chunk_index"] = i
            c["metadata"]["chunk_length"] = len(c["text"])
            
        return chunks

    def chunk_document(self, pages: List[Tuple[int, str]], document_name: str) -> List[dict]:
        start_time = time.perf_counter()
        all_chunks = []
        for page_number, page_text in pages:
            page_chunks = self.chunk_page(page_text, page_number, document_name)
            all_chunks.extend(page_chunks)

        duration_ms = (time.perf_counter() - start_time) * 1000
        rag_logger.info("Document chunking complete", extra={
            "document_name": document_name,
            "pages": len(pages),
            "total_chunks": len(all_chunks),
            "duration_ms": round(duration_ms, 2)
        })
        return all_chunks
